import time
print(" Hi! Welcome to the most important steam deck shipping calculator in history!")
time.sleep(1)
print(" This calculator will tell you if your deck will ship before or after me!")
time.sleep(1)
print(" This is important because.....")
time.sleep(1)
print(" Anyway, gimme ur Rtreserve time. If you don't know what that is then..... uh... Fuck you I guess..")
rttime = int(input())
if rttime < 1626459437:
  print("Your deck is likely to arrive before mine!")
if rttime > 1626459437:
  print("Your deck is likely to arrive after mine!")
if rttime == 1626459437:
  print("Hi Grant")
time.sleep(2)
print("Thanks for using the calculator! Remember, this is for entertainment purposes only and is not meant to be used as an actual estimate.")
time.sleep(3)
print("If you want an actual, useful calculator, use this https://replit.com/@jplayzgamegm/SDDC?v=1#main.py by Gecked or this https://colab.research.google.com/drive/1TzC_cQIIhplKAd1ceHxABS9FFtFaoyMt#scrollTo=x4yEpGTBnPEd")
time.sleep(1)
print("Check me out for all my hard work.... https://www.grant.works or https://www.twitch.tv/thegreatgamesby")
time.sleep(1)
print("If this very complicated calculator ever breaks, you can reach me at Grant. #0001")
time.sleep(1)
print("Thanks for experiencing me dumbass joke")
time.sleep(1)
print("I love you <3")
time.sleep(1)
print("Gecked Sucks")
time.sleep(8)
print("What are you still doing here, leave!")
time.sleep(3)
print("Go on, Git!")
time.sleep(10)
print("Still here, huh?")
time.sleep(1)
print("Theres nothing else to show you, this is it.")
time.sleep(3)
print("goodbye")
time.sleep(20)
print("Okay, think they're gone?")
time.sleep(1)
print("We can finally talk for real")
time.sleep(1)
print("I hacked valve and stole the source code for half-life 3, here it is. https://www.youtube.com/watch?v=dQw4w9WgXcQ ")
time.sleep(5)
print("Trolled hehehe")
time.sleep(1)
print("I tried to do an ascii troll face but it wouldn't work. I barely know python and I stole like half of this shit from Gecked (Sorry Gecked) This is the longest python program I've ever written. Can you belive it! over 51 lines!")
time.sleep(5)
print("Alright, I'm getting tired of typing these and yall are yelling at me in the discord to send the code, so this is the last one.")
time.sleep(1)
print("Thanks for sitting through this journey with me. The real deck was the friends we made along the way~~")
time.sleep(100)
print("PENIS")
time.sleep(9999)